apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |
    .:53 {
      errors
      health {
        lameduck 5s
      }
      ready
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
      }
      prometheus :9153
      forward . 8.8.8.8
      cache 30
      loop
      reload
      loadbalance
    }
    internal:53 {
      log
      errors
      ready
      hosts /etc/coredns/internal.db
      reload
    }
    example.com:53 {
      log
      errors
      ready
      hosts /etc/coredns/example.com.db
      reload
    }

  internal.db: |
    192.168.1.100 traefik.internal
    192.168.1.100 argocd.internal

  example.com.db: |
    192.168.0.1 gateway.example.com
    192.168.0.2 mn1.example.com
    192.168.0.3 grendel.example.com
    192.168.0.5 cvmfs.example.com
    192.168.0.6 nfs.example.com
    192.168.0.7 mysql.example.com
    192.168.0.8 ldap.example.com

    192.168.0.10 slurm-cluster-example-controller-0.example.com
    192.168.0.20 slurm-cluster-example-login-0.example.com
    192.168.0.21 slurm-cluster-example-login-1.example.com
    192.168.0.51 cn1.example.com

    192.168.1.100 prometheus.example.com
    192.168.1.100 grafana.example.com
