apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
      service-type: ClusterIP
  config:
    network:
      ingress-class: 'kourier.ingress.networking.knative.dev'
    # Create a DNS entry with *.knative.example.com as domain and the External LB IP address as IP.
    # Replace knative.example.com with your domain suffix.
    domain:
      'knative.example.com': ''
