deployment:
  kind: DaemonSet

ingressClass:
  enabled: true
  isDefaultClass: true

service:
  enabled: true
  annotations:
    metallb.universe.tf/address-pool: main-pool
    metallb.universe.tf/allow-shared-ip: traefik-lb-key
  spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: 192.168.1.100

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    namespaces: []
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    namespaces: []
    ingressClass: traefik
    publishedService:
      enabled: true

globalArguments:
  - '--global.checknewversion'
  - '--api.dashboard=true'

additionalArguments:
  - '--entryPoints.websecure.proxyProtocol.insecure'
  - '--entryPoints.websecure.forwardedHeaders.insecure'

ingressRoute:
  dashboard:
    enabled: true
    # See your DNS configuration
    matchRule: Host(`traefik.internal`)
    entryPoints: ['traefik']

# Configure ports
ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    protocol: TCP
  web:
    port: 80
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: true
    exposedPort: 443
    protocol: TCP
    # You MUST open port 443 UDP!
    # HTTP3 upgrades the connection from TCP to UDP.
    http3:
      enabled: true
    tls:
      enabled: true
  metrics:
    port: 9100
    expose: false
    exposedPort: 9100
    protocol: TCP

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

podSecurityContext:
  fsGroup: 65532
