apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cvmfs
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: CVMFS project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'

  destinations:
    - namespace: 'cvmfs'
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - kind: '*'
      group: '*'

  clusterResourceWhitelist:
    - kind: '*'
      group: '*'
