apiVersion: 'k8s.cni.cncf.io/v1'
kind: NetworkAttachmentDefinition
metadata:
  name: rook-cluster-net
  namespace: rook-ceph-cluster
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth0",
      "ipam":{
        "type":"whereabouts",
        "range": "10.11.0.0/24"
      }
    }
