apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  infra:
    nodePlacement:
      nodeSelector:
        node-role.kubernetes.io/control-plane: 'true'
  workloads:
    nodePlacement:
      nodeSelector: {}
